version: 2
jobs:
  build:

    working_directory: ~/esop

    docker:
      - image: cimg/openjdk:8.0

    steps:

      - checkout

      - restore_cache:
          keys:
            - m2-{{ checksum "pom.xml" }}
            - m2-

      - run: (echo "${google_application_credentials}" > /tmp/gcp.json) && mvn clean install -PsnapshotRepo,rpm,deb,cloudTests,localTests -DoutputDirectory=/tmp/artifacts -Dcassandra3.version=3.11.13 -Dcassandra4.version=4.1-alpha1

      - save_cache:
          paths:
            - ~/.m2
          key: m2-{{ checksum "pom.xml" }}

      - store_test_results:
          path: ~/esop/target/surefire-reports

      - store_artifacts:
          path: /tmp/artifacts

      - persist_to_workspace:
          root: /tmp/artifacts
          paths:
            - "esop*.jar"
            - "esop*.rpm"
            - "esop*.deb"

  publish-github-release:
    docker:
      - image: cimg/go:1.17
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            set -xue
            go install github.com/tcnksm/ghr@latest
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ./artifacts/

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /^esop-\d+\.\d+\.\d+$/
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^esop-\d+\.\d+\.\d+$/
